# Runs tests and linters on pushes to main and PRs.
name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - "main"
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/**"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # v1.94.1
        with:
          components: rustfmt, clippy
          toolchain: stable             
      - name: Set up Rust caching
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: Run rustfmt
        run: |
          cargo fmt -- --check
      - name: Run clippy
        run: |
          cargo clippy -- -D warnings
      - name: Run tests
        run: |
          cargo test
