# Builds binaries and uploads them to a GitHub release when a v* tag is pushed.
name: Publish release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
  build:
    name: Build release binaries
    runs-on: ${{ matrix.runner-os }}
    needs: create-release
    strategy:
      matrix:
        include:
          - runner-os: ubuntu-24.04
            rustc-target: "x86_64-unknown-linux-gnu"
          - runner-os: ubuntu-24.04
            rustc-target: "aarch64-unknown-linux-gnu"
          - runner-os: macos-latest
            rustc-target: "aarch64-apple-darwin"
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1.94.1
        with:
          toolchain: stable     
          targets: ${{ matrix.rustc-target }}
      - name: Build
        run: |
          cargo build --release
      - name: Create tarball
        run: |
          mkdir out
          cp target/release/docker-reaper out/
          cp README.md LICENSE-MIT LICENSE-APACHE CHANGELOG.md out/
          cd out && tar czf docker-reaper-${suffix}.tar.gz *
        env:
          suffix: ${{ matrix.rustc-target }}
      - name: Upload tarball
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: out/*.tar.gz
